<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <title><?= $title ?></title>
      <!-- Meta Tags -->
      <meta name="description" content="Angry Studio is a platform for web designers and developers where we share free website templates, UI snippets and high-quality web dev tutorials.">
      <!--  Search Engine Tags -->
      <meta itemprop="name" content="Yank - Free Bootstrap 4 Template">
      <meta itemprop="description" content="Angry Studio is a platform for web designers and developers where we share free website templates, UI snippets and high-quality web dev tutorials.">
      <meta itemprop="image" content="https://angrystudio.com/featured-image.png">
      <!-- Facebook OG Meta Tags -->
      <meta property="og:url" content="https://angrystudio.com/">
      <meta property="og:type" content="website">
      <meta property="og:title" content="Yank - Free Bootstrap 4 Template">
      <meta property="og:description" content="Angry Studio is a platform for web designers and developers where we share free website templates, UI snippets and high-quality web dev tutorials.">
      <meta property="og:image" content="https://angrystudio.com/featured-image.png">
      <!-- Twitter Cards Meta Tags -->
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:title" content="Yank - Free Bootstrap 4 Template">
      <meta name="twitter:description" content="Angry Studio is a platform for web designers and developers where we share free website templates, UI snippets and high-quality web dev tutorials.">
      <meta name="twitter:image" content="https://angrystudio.com/featured-image.png">
      <!-- Meta Tags Generated by https://angrystudio.com/tools/meta-tag-generator-for-website-seo/ -->
	  <link rel="icon" href="<?= site_url('assets/front-end/images/houses.png')?>" sizes="32x32" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i,800,800i,900,900i" rel="stylesheet">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css" rel="stylesheet">
      <link href="<?= site_url('assets/front-end/css/bootstrap.min.css')?>" rel="stylesheet">
      <link href="<?= site_url('assets/front-end/css/style.css')?>" rel="stylesheet">
       <!-- SweetAlert2 -->
      <link rel="stylesheet" href="<?= base_url('assets/login/vendor/sweetalert2/dist/sweetalert2.min.css')?>">
   </head>
   <body>